// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/telemetry/v1/telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sensor        string                 `protobuf:"bytes,1,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetSensor() string {
	if x != nil {
		return x.Sensor
	}
	return ""
}

func (x *Telemetry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Telemetry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      uint64                 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

var File_api_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	" api/telemetry/v1/telemetry.proto\x12\ftelemetry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n" +
	"\tTelemetry\x12\x16\n" +
	"\x06sensor\x18\x01 \x01(\tR\x06sensor\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"'\n" +
	"\tStreamAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived2V\n" +
	"\rTelemetrySink\x12E\n" +
	"\x0fStreamTelemetry\x12\x17.telemetry.v1.Telemetry\x1a\x17.telemetry.v1.StreamAck(\x01B<Z:github.com/kvoloboi/telemetry/api/telemetry/v1;telemetrypbb\x06proto3"

var (
	file_api_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_api_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telemetry_v1_telemetry_proto_rawDesc), len(file_api_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_api_telemetry_v1_telemetry_proto_rawDescData
}

var file_api_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_telemetry_v1_telemetry_proto_goTypes = []any{
	(*Telemetry)(nil),             // 0: telemetry.v1.Telemetry
	(*StreamAck)(nil),             // 1: telemetry.v1.StreamAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_telemetry_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.v1.Telemetry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: telemetry.v1.TelemetrySink.StreamTelemetry:input_type -> telemetry.v1.Telemetry
	1, // 2: telemetry.v1.TelemetrySink.StreamTelemetry:output_type -> telemetry.v1.StreamAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_telemetry_v1_telemetry_proto_init() }
func file_api_telemetry_v1_telemetry_proto_init() {
	if File_api_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telemetry_v1_telemetry_proto_rawDesc), len(file_api_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_api_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_telemetry_v1_telemetry_proto = out.File
	file_api_telemetry_v1_telemetry_proto_goTypes = nil
	file_api_telemetry_v1_telemetry_proto_depIdxs = nil
}
