// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/telemetry/v1/telemetry.proto

package telemetrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetrySink_StreamTelemetry_FullMethodName = "/telemetry.v1.TelemetrySink/StreamTelemetry"
)

// TelemetrySinkClient is the client API for TelemetrySink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetrySinkClient interface {
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Telemetry, StreamAck], error)
}

type telemetrySinkClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetrySinkClient(cc grpc.ClientConnInterface) TelemetrySinkClient {
	return &telemetrySinkClient{cc}
}

func (c *telemetrySinkClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Telemetry, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetrySink_ServiceDesc.Streams[0], TelemetrySink_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Telemetry, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetrySink_StreamTelemetryClient = grpc.ClientStreamingClient[Telemetry, StreamAck]

// TelemetrySinkServer is the server API for TelemetrySink service.
// All implementations must embed UnimplementedTelemetrySinkServer
// for forward compatibility.
type TelemetrySinkServer interface {
	StreamTelemetry(grpc.ClientStreamingServer[Telemetry, StreamAck]) error
	mustEmbedUnimplementedTelemetrySinkServer()
}

// UnimplementedTelemetrySinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetrySinkServer struct{}

func (UnimplementedTelemetrySinkServer) StreamTelemetry(grpc.ClientStreamingServer[Telemetry, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedTelemetrySinkServer) mustEmbedUnimplementedTelemetrySinkServer() {}
func (UnimplementedTelemetrySinkServer) testEmbeddedByValue()                       {}

// UnsafeTelemetrySinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetrySinkServer will
// result in compilation errors.
type UnsafeTelemetrySinkServer interface {
	mustEmbedUnimplementedTelemetrySinkServer()
}

func RegisterTelemetrySinkServer(s grpc.ServiceRegistrar, srv TelemetrySinkServer) {
	// If the following call panics, it indicates UnimplementedTelemetrySinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetrySink_ServiceDesc, srv)
}

func _TelemetrySink_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetrySinkServer).StreamTelemetry(&grpc.GenericServerStream[Telemetry, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetrySink_StreamTelemetryServer = grpc.ClientStreamingServer[Telemetry, StreamAck]

// TelemetrySink_ServiceDesc is the grpc.ServiceDesc for TelemetrySink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetrySink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.v1.TelemetrySink",
	HandlerType: (*TelemetrySinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _TelemetrySink_StreamTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/telemetry/v1/telemetry.proto",
}
